export type UrssafVoieType = {
  code: string;
  label: string;
};

export const URSSAF_VOIE_TYPES: UrssafVoieType[] = [
  { code: "ALL", label: "Allee" },
  { code: "AV", label: "Avenue" },
  { code: "BAT", label: "Batiment" },
  { code: "BD", label: "Boulevard" },
  { code: "C", label: "Cours" },
  { code: "CAN", label: "Canal" },
  { code: "CAS", label: "Caserne" },
  { code: "CAV", label: "Cavee" },
  { code: "CEI", label: "Ceinture" },
  { code: "CEL", label: "Cellier" },
  { code: "CEN", label: "Centre" },
  { code: "CGE", label: "College" },
  { code: "CH", label: "Chasse" },
  { code: "CHA", label: "Chateau" },
  { code: "CHE", label: "Chemin" },
  { code: "CHN", label: "Chantier" },
  { code: "CHP", label: "Chapelle" },
  { code: "CHS", label: "Chaussee" },
  { code: "CHT", label: "Cheminement" },
  { code: "CHV", label: "Chemin vicinal" },
  { code: "CI", label: "Cite" },
  { code: "CIM", label: "Cimetiere" },
  { code: "CIN", label: "Cinema" },
  { code: "CL", label: "Clos" },
  { code: "CLB", label: "Club" },
  { code: "CLI", label: "Clinique" },
  { code: "CLL", label: "Col" },
  { code: "CLO", label: "Cloitre" },
  { code: "CN", label: "Coin" },
  { code: "CO", label: "Cour" },
  { code: "COE", label: "Colline" },
  { code: "COG", label: "Cottage" },
  { code: "COL", label: "Colonie" },
  { code: "COM", label: "Commissariat" },
  { code: "COR", label: "Corniche" },
  { code: "COT", label: "Cote" },
  { code: "COU", label: "Couloir" },
  { code: "CRO", label: "Carroi" },
  { code: "CRX", label: "Croix" },
  { code: "CTE", label: "Central telephonique" },
  { code: "CUR", label: "Cure" },
  { code: "DEG", label: "Degre" },
  { code: "DEP", label: "Depot" },
  { code: "DES", label: "Descente" },
  { code: "DIG", label: "Digue" },
  { code: "DOM", label: "Domaine" },
  { code: "DON", label: "Direction" },
  { code: "ECA", label: "Ecart" },
  { code: "ECL", label: "Ecluse" },
  { code: "ECO", label: "Ecole" },
  { code: "ECV", label: "Enclave" },
  { code: "EGL", label: "Eglise" },
  { code: "EMP", label: "Emplacement" },
  { code: "EN", label: "Enceinte" },
  { code: "ENC", label: "Enclos" },
  { code: "ENT", label: "Entrepot" },
  { code: "ESC", label: "Escalier" },
  { code: "ESP", label: "Esplanade" },
  { code: "ETA", label: "Etablissement" },
  { code: "ETG", label: "Etang" },
  { code: "FAC", label: "Facade" },
  { code: "FCU", label: "Faculte" },
  { code: "FER", label: "Ferme" },
  { code: "FG", label: "Faubourg" },
  { code: "FOL", label: "Folie" },
  { code: "FON", label: "Fontaine" },
  { code: "FOR", label: "Foret" },
  { code: "FOS", label: "Fosse" },
  { code: "FOY", label: "Foyer" },
  { code: "FRI", label: "Friche" },
  { code: "FT", label: "Fort" },
  { code: "GA", label: "Gare" },
  { code: "GAL", label: "Galerie" },
  { code: "GDI", label: "Grand impasse" },
  { code: "GED", label: "Gendarmerie" },
  { code: "GEN", label: "Grand ensemble" },
  { code: "GGE", label: "Garage" },
  { code: "GLA", label: "Glacis" },
  { code: "GPE", label: "Groupe" },
  { code: "GR", label: "Grand rue" },
  { code: "GRI", label: "Grille" },
  { code: "GRN", label: "Garenne" },
  { code: "GRP", label: "Groupement" },
  { code: "GSC", label: "Groupe scolaire" },
  { code: "GUE", label: "Gue" },
  { code: "HA", label: "Halage" },
  { code: "HAL", label: "Halle" },
  { code: "HAM", label: "Hameau" },
  { code: "HCE", label: "Hospice" },
  { code: "HIP", label: "Hippodrome" },
  { code: "HLM", label: "H.L.M." },
  { code: "HOP", label: "Hopital" },
  { code: "HOT", label: "Hotel" },
  { code: "HUT", label: "Hutte" },
  { code: "ILE", label: "Ile" },
  { code: "ILO", label: "Ilot" },
  { code: "IMB", label: "Immeuble" },
  { code: "IMP", label: "Impasse" },
  { code: "INS", label: "Institut" },
  { code: "ISP", label: "Inspection" },
  { code: "JAR", label: "Jardin" },
  { code: "JET", label: "Jetee" },
  { code: "JUS", label: "Justice" },
  { code: "LD", label: "Lieu dit" },
  { code: "LEV", label: "Levee" },
  { code: "LOT", label: "Lotissement" },
  { code: "LYC", label: "Lycee" },
  { code: "MA", label: "Mare" },
  { code: "MAG", label: "Magasin" },
  { code: "MAI", label: "Maison" },
  { code: "MAN", label: "Manoir" },
  { code: "MAR", label: "Marche" },
  { code: "MAS", label: "Mas" },
  { code: "MAT", label: "Maternite" },
  { code: "MET", label: "Metro" },
  { code: "MF", label: "Maison forestiere" },
  { code: "MG", label: "Maison de garde" },
  { code: "ML", label: "Mail" },
  { code: "MOU", label: "Moulin" },
  { code: "MRI", label: "Mairie" },
  { code: "MTE", label: "Montee" },
  { code: "MUS", label: "Musee" },
  { code: "NTE", label: "Nouvelle route" },
  { code: "OBS", label: "Observatoire" },
  { code: "OCT", label: "Octroi" },
  { code: "PA", label: "Parvis" },
  { code: "PAE", label: "Petite avenue" },
  { code: "PAL", label: "Palais" },
  { code: "PAR", label: "Parc" },
  { code: "PAS", label: "Passage" },
  { code: "PAT", label: "Pature" },
  { code: "PAV", label: "Pavillon" },
  { code: "PBY", label: "Presbytere" },
  { code: "PCE", label: "Porche" },
  { code: "PER", label: "Perystile" },
  { code: "PHA", label: "Pharmacie" },
  { code: "PIE", label: "Piece" },
  { code: "PIM", label: "Petite impasse" },
  { code: "PKG", label: "Parking" },
  { code: "PL", label: "Place" },
  { code: "PLA", label: "Plaine" },
  { code: "PLC", label: "Placis" },
  { code: "PLE", label: "Passerelle" },
  { code: "PLT", label: "Plateau" },
  { code: "PLY", label: "Petit lycee" },
  { code: "PO", label: "Pont" },
  { code: "POI", label: "Pointe" },
  { code: "POR", label: "Porte" },
  { code: "POT", label: "Poterne" },
  { code: "POU", label: "Pourtour" },
  { code: "PPA", label: "Petit passage" },
  { code: "PR", label: "Petite rue" },
  { code: "PRA", label: "Prairie" },
  { code: "PRE", label: "Pre" },
  { code: "PRO", label: "Promenade" },
  { code: "PRQ", label: "Presquile" },
  { code: "PRT", label: "Petite route" },
  { code: "PRU", label: "Preau" },
  { code: "PT", label: "Port" },
  { code: "PTE", label: "Poste" },
  { code: "Q", label: "Quai" },
  { code: "QU", label: "Quartier" },
  { code: "R", label: "Rue" },
  { code: "RAC", label: "Raccourci" },
  { code: "RAM", label: "Rampe" },
  { code: "REM", label: "Rempart" },
  { code: "RES", label: "Residence" },
  { code: "RNT", label: "Restaurant" },
  { code: "ROC", label: "Rocade" },
  { code: "ROQ", label: "Roquet" },
  { code: "ROT", label: "Rotonde" },
  { code: "ROU", label: "Roulade" },
  { code: "RP", label: "Rond point" },
  { code: "RTE", label: "Route" },
  { code: "RUL", label: "Ruelle" },
  { code: "SAN", label: "Sanatorium" },
  { code: "SAP", label: "Sapum" },
  { code: "SAS", label: "Sas" },
  { code: "SCE", label: "Service" },
  { code: "SEC", label: "Section" },
  { code: "SEM", label: "Seminaire" },
  { code: "SEN", label: "Sentier" },
  { code: "SNT", label: "Sente" },
  { code: "SOC", label: "Societe" },
  { code: "SQ", label: "Square" },
  { code: "STA", label: "Stade" },
  { code: "STN", label: "Stand" },
  { code: "STO", label: "Station" },
  { code: "TE", label: "Terrasse" },
  { code: "TEA", label: "Terrain" },
  { code: "TEN", label: "Tenue" },
  { code: "TER", label: "Tertre" },
  { code: "THE", label: "Theatre" },
  { code: "TOU", label: "Tour" },
  { code: "TP", label: "Terre plein" },
  { code: "TRA", label: "Traverse" },
  { code: "TRG", label: "Triege" },
  { code: "TRI", label: "Triage" },
  { code: "TUI", label: "Tuilerie" },
  { code: "USI", label: "Usine" },
  { code: "VAL", label: "Val" },
  { code: "VCH", label: "Vieux chemin" },
  { code: "VEL", label: "Velodrome" },
  { code: "VEN", label: "Venelle" },
  { code: "VGE", label: "Village" },
  { code: "VIA", label: "Viaduc" },
  { code: "VIL", label: "Ville" },
  { code: "VLA", label: "Villa" },
  { code: "VLE", label: "Vallee" },
  { code: "VNO", label: "Ville nouvelle" },
  { code: "VO", label: "Voie" },
  { code: "VON", label: "Vallon" },
  { code: "VOY", label: "Voyeul" },
  { code: "ZAC", label: "ZAC" },
  { code: "ZI", label: "Zone industrielle" },
  { code: "ZUP", label: "Z.U.P." },
];

export function getUrssafVoieTypeLabel(code?: string) {
  const voieType = URSSAF_VOIE_TYPES.find((item) => item.code === code);
  return voieType ? `${voieType.code} - ${voieType.label}` : "";
}
